'use client';
import {useEffect,useMemo,useState} from 'react';
import {loadState,saveState,ensureCharacter,uid,State,Message,Character,Diary,Moment,EventItem} from './lib/store';

type Tab='home'|'chat'|'contacts'|'memory'|'diary'|'calendar'|'moments'|'settings';
const nav: {id:Tab;icon:string;label:string}[]=[{id:'home',icon:'⌂',label:'首页'},{id:'chat',icon:'💬',label:'聊天'},{id:'contacts',icon:'👥',label:'联系人'},{id:'memory',icon:'🧠',label:'记忆'},{id:'diary',icon:'📔',label:'日记'},{id:'calendar',icon:'🗓',label:'日历'},{id:'moments',icon:'✨',label:'动态'},{id:'settings',icon:'⚙︎',label:'设置'}];

export default function Home(){
 const [state,setState]=useState<State>(()=>ensureCharacter(loadState()));
 const [tab,setTab]=useState<Tab>('home'); const [selected,setSelected]=useState('');
 useEffect(()=>saveState(state),[state]);
 useEffect(()=>{ if(!selected&&state.characters[0]) setSelected(state.characters[0].id); },[state.characters,selected]);
 const character=state.characters.find(c=>c.id===selected)||state.characters[0];
 const set=(patch:Partial<State>)=>setState(s=>({...s,...patch}));
 const updateSettings=(p:Partial<State['settings']>)=>setState(s=>({...s,settings:{...s.settings,...p}}));
 return <main className="phone"><section className="screen">
  <Status/>
  {tab==='home'&&<HomeView state={state} go={setTab} onOpenChat={(id)=>{setSelected(id);setTab('chat')}}/>}
  {tab==='chat'&&character&&<ChatView state={state} character={character} setState={setState} settings={state.settings}/>} 
  {tab==='contacts'&&<ContactsView state={state} setState={setState} openChat={(id)=>{setSelected(id);setTab('chat')}}/>}
  {tab==='memory'&&character&&<MemoryView state={state} setState={setState} character={character}/>} 
  {tab==='diary'&&<DiaryView state={state} setState={setState}/>} 
  {tab==='calendar'&&<CalendarView state={state} setState={setState}/>} 
  {tab==='moments'&&<MomentsView state={state} setState={setState}/>} 
  {tab==='settings'&&<SettingsView state={state} update={updateSettings} setState={setState}/>} 
  <nav className="bottom">{nav.slice(0,5).map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>setTab(n.id)}><b>{n.icon}</b><small>{n.label}</small></button>)}</nav>
 </section></main>
}
function Status(){const [t,setT]=useState('');useEffect(()=>{const f=()=>setT(new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit'}).format(new Date()));f();const x=setInterval(f,1000);return()=>clearInterval(x)},[]);return <div className="status"><span>{t}</span><span>▮▮▮ ᯤ ▰</span></div>}
function Header({title,back}:{title:string;back?:()=>void}){return <div className="pageHead">{back&&<button onClick={back}>‹</button>}<strong>{title}</strong></div>}
function HomeView({state,go,onOpenChat}:{state:State;go:(t:Tab)=>void;onOpenChat:(id:string)=>void}){const c=state.characters[0];return <div className="view homeView"><div className="hero glass"><div className="heroOrb">{c?.avatar||'🌙'}</div><h1>M叽</h1><p>你的 AI 小手机</p><span className="online">● 本地数据已启用</span></div><div className="homeGrid">{nav.slice(1).map(n=><button key={n.id} onClick={()=>go(n.id)}><span>{n.icon}</span><label>{n.label}</label></button>)}</div>{c&&<button className="chatCard glass" onClick={()=>onOpenChat(c.id)}><span className="avatar">{c.avatar}</span><span><b>{c.name}</b><small>{state.messages[c.id]?.length?`继续上次聊天 · ${state.messages[c.id].length} 条消息`:'开始第一次聊天'}</small></span><i>›</i></button>}<p className="tip">Safari → 分享 → 添加到主屏幕，即可像 App 一样使用。</p></div>}
function ChatView({state,character,setState,settings}:{state:State;character:Character;setState:React.Dispatch<React.SetStateAction<State>>;settings:State['settings']}){const [text,setText]=useState('');const [busy,setBusy]=useState(false);const [err,setErr]=useState('');const messages=state.messages[character.id]||[];const send=async()=>{const v=text.trim();if(!v||busy)return;setText('');setErr('');const user:Message={id:uid(),role:'user',content:v,time:Date.now()};const next=[...messages,user];setState(s=>({...s,messages:{...s.messages,[character.id]:next}}));if(!settings.baseUrl||!settings.model){setErr('请先在「设置」填写 API Base URL 和模型。');return}setBusy(true);try{const memories=(state.memories[character.id]||[]).slice(-20);const system=[character.system,memories.length?`长期记忆：\n${memories.join('\n')}`:''].filter(Boolean).join('\n\n');const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:settings.baseUrl,apiKey:settings.apiKey,model:settings.model,temperature:settings.temperature,maxTokens:settings.maxTokens,messages:[{role:'system',content:system},...next.slice(-40).map(m=>({role:m.role,content:m.content}))]})});const data=await r.json();if(!r.ok)throw new Error(data.error||'API 请求失败');const content=data?.choices?.[0]?.message?.content||data?.choices?.[0]?.text;if(!content)throw new Error('API 没有返回文本');const ai:Message={id:uid(),role:'assistant',content,time:Date.now()};setState(s=>({...s,messages:{...s.messages,[character.id]:[...(s.messages[character.id]||[]),ai]}}));}catch(e:any){setErr(e.message||'发送失败')}finally{setBusy(false)}};return <div className="view chatView"><Header title={character.name}/><div className="chatStatus">{character.avatar}　{character.status}</div><div className="messages">{messages.length===0&&<div className="empty"><div>{character.avatar}</div><b>和 {character.name} 开始聊天</b><span>消息和设置保存在你的设备浏览器中。</span></div>}{messages.map(m=><div key={m.id} className={'bubbleRow '+m.role}><div className="bubble">{m.content}</div><time>{new Date(m.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div>)}{busy&&<div className="bubbleRow assistant"><div className="bubble typing">● ● ●</div></div>}</div>{err&&<div className="error">{err}</div>}<div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="输入消息…" rows={1}/><button onClick={send} disabled={busy||!text.trim()}>↑</button></div></div>}
function ContactsView({state,setState,openChat}:{state:State;setState:React.Dispatch<React.SetStateAction<State>>;openChat:(id:string)=>void}){const [name,setName]=useState('');const [system,setSystem]=useState('');const add=()=>{if(!name.trim())return;const c:Character={id:uid(),name:name.trim(),avatar:'🌙',system:system.trim()||'你是一个自然、细腻、有长期记忆的 AI 角色。请保持人格一致，用自然聊天方式回应。',status:'在线',createdAt:Date.now()};setState(s=>({...s,characters:[...s.characters,c],messages:{...s.messages,[c.id]:[]},memories:{...s.memories,[c.id]:[]}}));setName('');setSystem('')};return <div className="view"><Header title="联系人"/><div className="card form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="角色名称"/><textarea value={system} onChange={e=>setSystem(e.target.value)} placeholder="角色设定 / System Prompt（可选）"/><button className="primary" onClick={add}>＋ 添加角色</button></div><div className="list">{state.characters.map(c=><div className="rowCard" key={c.id}><span className="avatar">{c.avatar}</span><div><b>{c.name}</b><small>{c.status} · {state.messages[c.id]?.length||0} 条消息</small></div><button onClick={()=>openChat(c.id)}>聊天 ›</button></div>)}</div></div>}
function MemoryView({state,setState,character}:{state:State;setState:React.Dispatch<React.SetStateAction<State>>;character:Character}){const [v,setV]=useState('');const list=state.memories[character.id]||[];const add=()=>{if(!v.trim())return;setState(s=>({...s,memories:{...s.memories,[character.id]:[...(s.memories[character.id]||[]),v.trim()]}}));setV('')};return <div className="view"><Header title="记忆"/><div className="subHead">{character.avatar} {character.name} 的长期记忆</div><div className="card form"><textarea value={v} onChange={e=>setV(e.target.value)} placeholder="添加一条重要记忆…"/><button className="primary" onClick={add}>保存记忆</button></div><div className="memoryList">{list.length?list.map((x,i)=><div className="memory" key={i}><span>🧠</span><p>{x}</p><button onClick={()=>setState(s=>({...s,memories:{...s.memories,[character.id]:(s.memories[character.id]||[]).filter((_,j)=>j!==i)}}))}>×</button></div>):<Empty text="还没有长期记忆"/>}</div></div>}
function DiaryView({state,setState}:{state:State;setState:React.Dispatch<React.SetStateAction<State>>}){const [title,setTitle]=useState('');const [content,setContent]=useState('');const add=()=>{if(!content.trim())return;const d:Diary={id:uid(),title:title.trim()||'无题',content,date:new Date().toLocaleDateString('zh-CN'),mood:'☁️'};setState(s=>({...s,diaries:[d,...s.diaries]}));setTitle('');setContent('')};return <div className="view"><Header title="日记"/><div className="card form"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="标题"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="写下今天的事情…"/><button className="primary" onClick={add}>保存日记</button></div>{state.diaries.map(d=><article className="note" key={d.id}><small>{d.date}　{d.mood}</small><h3>{d.title}</h3><p>{d.content}</p><button onClick={()=>setState(s=>({...s,diaries:s.diaries.filter(x=>x.id!==d.id)}))}>删除</button></article>)}</div>}
function CalendarView({state,setState}:{state:State;setState:React.Dispatch<React.SetStateAction<State>>}){const [title,setTitle]=useState('');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [time,setTime]=useState('20:00');const add=()=>{if(!title.trim())return;const e:EventItem={id:uid(),title,date,time,note:''};setState(s=>({...s,events:[...s.events,e].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))}));setTitle('')};return <div className="view"><Header title="日历"/><div className="card form"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="事件名称"/><div className="two"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></div><button className="primary" onClick={add}>＋ 添加事件</button></div>{state.events.length?state.events.map(e=><div className="event" key={e.id}><div><b>{e.title}</b><small>{e.date} · {e.time}</small></div><button onClick={()=>setState(s=>({...s,events:s.events.filter(x=>x.id!==e.id)}))}>×</button></div>):<Empty text="暂无日程"/>}</div>}
function MomentsView({state,setState}:{state:State;setState:React.Dispatch<React.SetStateAction<State>>}){const [v,setV]=useState('');const add=()=>{if(!v.trim())return;const m:Moment={id:uid(),content:v.trim(),date:new Date().toLocaleString('zh-CN'),likes:0};setState(s=>({...s,moments:[m,...s.moments]}));setV('')};return <div className="view"><Header title="动态"/><div className="card form"><textarea value={v} onChange={e=>setV(e.target.value)} placeholder="有什么想分享的吗？"/><button className="primary" onClick={add}>发布</button></div>{state.moments.map(m=><article className="moment" key={m.id}><div className="avatar">🌙</div><div><b>M叽</b><small>{m.date}</small><p>{m.content}</p><button onClick={()=>setState(s=>({...s,moments:s.moments.map(x=>x.id===m.id?{...x,likes:x.likes+1}:x)}))}>♡ {m.likes}</button></div></article>)}</div>}
function SettingsView({state,update,setState}:{state:State;update:(p:Partial<State['settings']>)=>void;setState:React.Dispatch<React.SetStateAction<State>>}){const s=state.settings;const [show,setShow]=useState(false);return <div className="view"><Header title="设置"/><div className="section"><h3>AI API</h3><div className="card form"><label>Base URL<input value={s.baseUrl} onChange={e=>update({baseUrl:e.target.value})} placeholder="https://api.example.com/v1"/></label><label>API Key<div className="secret"><input type={show?'text':'password'} value={s.apiKey} onChange={e=>update({apiKey:e.target.value})}/><button onClick={()=>setShow(!show)}>{show?'隐藏':'显示'}</button></div></label><label>Model<input value={s.model} onChange={e=>update({model:e.target.value})} placeholder="例如 gpt-4o-mini"/></label><div className="two"><label>Temperature<input type="number" min="0" max="2" step="0.1" value={s.temperature} onChange={e=>update({temperature:Number(e.target.value)})}/></label><label>Max tokens<input type="number" min="100" value={s.maxTokens} onChange={e=>update({maxTokens:Number(e.target.value)})}/></label></div><p className="muted">API Key 只保存在本机浏览器 localStorage，并通过当前站点代理请求，不写入代码仓库。</p></div></div><div className="section"><h3>数据</h3><div className="card actions"><button onClick={()=>{if(confirm('清空所有聊天记录？'))setState(x=>({...x,messages:{}}))}}>清空聊天记录</button><button onClick={()=>{if(confirm('恢复所有本地数据？此操作不可撤销。')){localStorage.removeItem('mji-ios-v1');location.reload()}}}>重置全部数据</button></div></div><div className="section"><h3>关于</h3><div className="card about"><b>M叽 · iOS Web</b><span>把原 Android 版的核心体验移到 iPhone 浏览器。</span><small>数据默认保存在本机，不依赖账号。</small></div></div></div>}
function Empty({text}:{text:string}){return <div className="empty"><div>🌙</div><span>{text}</span></div>}
